baseurl = "https://example.com/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Bootstrap demo"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap-5"

[taxonomies]
category = "categories"
tag = "tags"

# Google analytics
# googleAnalytics = ""

[languages.en]
languageName = "English"

# Replace the default footer message with a localized message
# copyright = "Hugo template made with ❤ by AuthorGithub"

[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[languages.en.menu.main]]
name = "About"
url = "/about/"
weight = 2
[[languages.en.menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[languages.es]
languageName = "Español"

[[languages.es.menu.main]]
name = "Casa"
url = "/es/"
weight = 1
[[languages.es.menu.main]]
name = "Acerca de"
url = "/about/"
weight = 2
[[languages.es.menu.main]]
name = "Contacto"
url = "/contact/"
weight = 3

[languages.de]
languageName = "Deutsch"

[[languages.de.menu.main]]
name = "Start"
url = "/de/"
weight = 1
[[languages.de.menu.main]]
name = "Über uns"
url = "/about/"
weight = 2
[[languages.de.menu.main]]
name = "Kontakt"
url = "/contact/"
weight = 3

# Links format

[permalinks]
post = "/:year/:month/:title/"

[params]
# Main sections (currently used for the recent posts in the sidebar)
mainSections = ["post"]

# Default author
author = "John Doe"

# Date format (default: Jan 2, 2006)
# date_format = "Jan 2, 2006"

# Display post summaries instead of content in list templates (default: true)
# truncate = false

[params.sidebar]
# Whether to show the recent posts or not (default: true)
# showRecent = false

# Whether to show the taxonomies or not (default: true)
# showTaxonomy = false

# How many posts to show on the sidebar (Default: 5)
# num_recent_posts = 5

[params.header]
# Color scheme for the header (default: "light")
# colorScheme = "dark"

[params.footer]
# Color scheme for the footer (default: "light")
# colorScheme = "dark"
